/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package azamak;

import azamak.tts.TextToSpeech;
import azamak.utils.Config;
import azamak.utils.StrUtils;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.List;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Caret;
import marytts.signalproc.effects.JetPilotEffect;
import marytts.signalproc.effects.LpcWhisperiserEffect;
import marytts.signalproc.effects.RobotiserEffect;
import marytts.signalproc.effects.StadiumEffect;
import marytts.signalproc.effects.VocalTractLinearScalerEffect;
import marytts.signalproc.effects.VolumeEffect;

/**
 *
 * @author Azamak
 */
public class Interface extends javax.swing.JFrame {

    public Config confYemba;
    public Config confBassa;
    public static String fileToUpload = "";
    public static ArrayList<String> allWords;
    public Map<String, String> allYembaWords;
    public Map<String, String> allBassaWords;

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        parcourirBtn.setEnabled(false);
        addWordBtn.setEnabled(false);
        panneauAdmin.setVisible(false);
        panneauTraduction.setVisible(true);
        confYemba = new Config("francais-yemba.properties");
        confBassa = new Config("francais-bassa.properties");
        allYembaWords = confYemba.loadAllIn();
        allBassaWords = confBassa.loadAllIn();
        Set<String> set = new LinkedHashSet<>(allYembaWords.keySet());
        set.addAll(allBassaWords.keySet());
        allWords = new ArrayList<>(set);
        francaisTxtField.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void removeUpdate(DocumentEvent e) {
                yembaTxtField.setText(StrUtils.translate(francaisTxtField.getText(), confYemba));
                bassaTxtField.setText(StrUtils.translate(francaisTxtField.getText(), confBassa));
            }

            @Override
            public void insertUpdate(DocumentEvent e) {

                yembaTxtField.setText(StrUtils.translate(francaisTxtField.getText(), confYemba));
                bassaTxtField.setText(StrUtils.translate(francaisTxtField.getText(), confBassa));
            }

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                yembaTxtField.setText(StrUtils.translate(francaisTxtField.getText(), confYemba));
                bassaTxtField.setText(StrUtils.translate(francaisTxtField.getText(), confBassa));
            }

            public void keyReleased(KeyEvent e) {
                popupmenu.removeAll();
                popupmenu.add(new JMenuItem("bonjour"));
//                Rectangle rectangle = francaisTxtField.modelToView( francaisTxtField.getCaretPostion() );
                Caret caret = francaisTxtField.getCaret();

                Point p = caret.getMagicCaretPosition();
                System.out.println(" point = " + p.hashCode());
//                p.x += francaisTxtField.getLocationOnScreen().x;
//                p.y += francaisTxtField.getLocationOnScreen().y;
                System.out.println("x = " + ((int) p.getX()) + " y = " + ((int) p.getY()));
                popupmenu.show(francaisTxtField, (int) p.x, (int) p.y);
                popupmenu.requestFocus();
                popupmenu.grabFocus();
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupmenu = new javax.swing.JPopupMenu();
        jPanel4 = new javax.swing.JPanel();
        panneauTraduction = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        francaisTxtField = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        bassaTxtField = new javax.swing.JTextArea();
        BtnBassa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        yembaTxtField = new javax.swing.JTextArea();
        BtnYemba = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        volumeYemba = new javax.swing.JSlider();
        volumeBassa = new javax.swing.JSlider();
        panneauAdmin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableMot = new javax.swing.JTable();
        BtnRetour = new javax.swing.JButton();
        choixLangueCmb = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        motFrancais = new javax.swing.JTextField();
        motTraduit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fileToImportTxf = new javax.swing.JTextField();
        parcourirBtn = new javax.swing.JButton();
        addWordBtn = new javax.swing.JButton();
        importbtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new java.awt.CardLayout());

        panneauTraduction.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("AZAMAK");

        jLabel9.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("( Votre traducteur multilingue)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Panneau de traduction"));

        francaisTxtField.setBackground(new java.awt.Color(255, 255, 255));
        francaisTxtField.setColumns(20);
        francaisTxtField.setForeground(new java.awt.Color(0, 0, 0));
        francaisTxtField.setRows(5);
        francaisTxtField.setToolTipText("Texte à traduire");
        francaisTxtField.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                francaisTxtFieldInputMethodTextChanged(evt);
            }
        });
        francaisTxtField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                francaisTxtFieldKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(francaisTxtField);

        bassaTxtField.setBackground(new java.awt.Color(255, 255, 255));
        bassaTxtField.setColumns(20);
        bassaTxtField.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        bassaTxtField.setForeground(new java.awt.Color(0, 0, 0));
        bassaTxtField.setRows(5);
        bassaTxtField.setAutoscrolls(false);
        bassaTxtField.setBorder(javax.swing.BorderFactory.createTitledBorder("Traduction Bassa"));
        jScrollPane2.setViewportView(bassaTxtField);

        BtnBassa.setText("Lire...");
        BtnBassa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBassaActionPerformed(evt);
            }
        });

        yembaTxtField.setBackground(new java.awt.Color(255, 255, 255));
        yembaTxtField.setColumns(20);
        yembaTxtField.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        yembaTxtField.setForeground(new java.awt.Color(0, 0, 0));
        yembaTxtField.setRows(5);
        yembaTxtField.setBorder(javax.swing.BorderFactory.createTitledBorder("Traduction Yemba"));
        jScrollPane3.setViewportView(yembaTxtField);

        BtnYemba.setText("Lire...");
        BtnYemba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnYembaActionPerformed(evt);
            }
        });

        jLabel2.setText("Texte en Français  :");

        volumeYemba.setPaintLabels(true);
        volumeYemba.setPaintTicks(true);
        volumeYemba.setToolTipText("Volume");
        volumeYemba.setValue(0);

        volumeBassa.setPaintLabels(true);
        volumeBassa.setPaintTicks(true);
        volumeBassa.setToolTipText("Volume");
        volumeBassa.setValue(0);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BtnBassa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(volumeBassa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(BtnYemba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(volumeYemba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnYemba)
                        .addComponent(BtnBassa))
                    .addComponent(volumeYemba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(volumeBassa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panneauTraductionLayout = new javax.swing.GroupLayout(panneauTraduction);
        panneauTraduction.setLayout(panneauTraductionLayout);
        panneauTraductionLayout.setHorizontalGroup(
            panneauTraductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panneauTraductionLayout.setVerticalGroup(
            panneauTraductionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauTraductionLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(panneauTraduction, "card2");

        tableMot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mot en français", "Mot traduit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableMot);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        BtnRetour.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        BtnRetour.setText("<< Retour");
        BtnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRetourActionPerformed(evt);
            }
        });

        choixLangueCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sélectionner une langue", "Yemba", "Bassa" }));
        choixLangueCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choixLangueCmbItemStateChanged(evt);
            }
        });

        jLabel3.setText("Langue         :");

        jLabel4.setText("Mot(s) en français   : ");

        motFrancais.setBackground(new java.awt.Color(255, 255, 255));

        motTraduit.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Mot(s) traduit(s)  : ");

        jLabel6.setText("Charger un fichier  :");

        fileToImportTxf.setEditable(false);
        fileToImportTxf.setBackground(new java.awt.Color(204, 204, 204));

        parcourirBtn.setText("...");
        parcourirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcourirBtnActionPerformed(evt);
            }
        });

        addWordBtn.setText("Ajouter");
        addWordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWordBtnActionPerformed(evt);
            }
        });

        importbtn.setText("importer");
        importbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panneauAdminLayout = new javax.swing.GroupLayout(panneauAdmin);
        panneauAdmin.setLayout(panneauAdminLayout);
        panneauAdminLayout.setHorizontalGroup(
            panneauAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panneauAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panneauAdminLayout.createSequentialGroup()
                        .addComponent(BtnRetour)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panneauAdminLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(choixLangueCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauAdminLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(panneauAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauAdminLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fileToImportTxf, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(parcourirBtn)
                        .addGap(18, 18, 18)
                        .addComponent(importbtn)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panneauAdminLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(motFrancais, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panneauAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addWordBtn)
                            .addGroup(panneauAdminLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(motTraduit, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))))
        );
        panneauAdminLayout.setVerticalGroup(
            panneauAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneauAdminLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panneauAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choixLangueCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panneauAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(motFrancais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(motTraduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addWordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panneauAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fileToImportTxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parcourirBtn)
                    .addComponent(importbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRetour)
                .addGap(16, 16, 16))
        );

        jPanel4.add(panneauAdmin, "card3");

        jMenu1.setText("Fichier");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Nettoyer");
        jMenu1.add(jMenuItem1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Fermer");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Administration");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("+ Ajout des mots");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Aide");

        jMenuItem3.setText("Documentation");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("A propos");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBassaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBassaActionPerformed
        if (!"".equals(bassaTxtField.getText())) {
            if(volumeBassa.getValue() != 0){
            BtnBassa.setEnabled(false);
            readText(bassaTxtField.getText(), volumeBassa.getValue());
            BtnBassa.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Bien vouloir augmenter le volume"); 
            }
        }
    }//GEN-LAST:event_BtnBassaActionPerformed

    private void BtnYembaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnYembaActionPerformed
        // TODO add your handling code here:
        // lire en Yemba ŋ
        if (!"".equals(yembaTxtField.getText())) {
            if(volumeYemba.getValue() != 0){
            BtnYemba.setEnabled(false);
            readText(yembaTxtField.getText(), volumeYemba.getValue());
            BtnYemba.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Bien vouloir augmenter le volume"); 
            }
        }


    }//GEN-LAST:event_BtnYembaActionPerformed

    private void francaisTxtFieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_francaisTxtFieldInputMethodTextChanged
        // TODO add your handling code here:
        yembaTxtField.setText(StrUtils.translate(francaisTxtField.getText(), confYemba));
    }//GEN-LAST:event_francaisTxtFieldInputMethodTextChanged
    
    private void readText(String text, int volume) {
        TextToSpeech tts = new TextToSpeech();
        //=========================================================================
        //======================= Print available AUDIO EFFECTS ====================
        //=========================================================================

        //Print all the available audio effects
//        tts.getAudioEffects().stream().forEach(audioEffect -> {
//            System.out.println("-----Name-----");
//            System.out.println(audioEffect.getName());
//            System.out.println("-----Examples-----");
//            System.out.println(audioEffect.getExampleParameters());
//            System.out.println("-----Help Text------");
//            System.out.println(audioEffect.getHelpText() + "\n\n");
//
//        });

        //=========================================================================
        //========================= Print available voices =========================
        //=========================================================================
        //Print all the available voices
        tts.getAvailableVoices().stream().forEach(voice -> System.out.println("Voice: " + voice));

        // Setting the Current Voice
        tts.setVoice("cmu-rms-hsmm");

        //=========================================================================
        //========================= Let's try different effects=====================
        //=========================================================================
        //----- Hey you !-> check the help that is being printed on the console
        //----- You will understand how to use the effects better :)
        //VocalTractLinearScalerEffect
//        VocalTractLinearScalerEffect vocalTractLSE = new VocalTractLinearScalerEffect(); //russian drunk effect
//        vocalTractLSE.setParams("amount:70");
//
//        //JetPilotEffect
//        JetPilotEffect jetPilotEffect = new JetPilotEffect(); //epic fun!!!
//        jetPilotEffect.setParams("amount:100");
//
//        //RobotiserEffect
//        RobotiserEffect robotiserEffect = new RobotiserEffect();
//        robotiserEffect.setParams("amount:50");

        //StadiumEffect
        StadiumEffect stadiumEffect = new StadiumEffect();
        stadiumEffect.setParams("amount:" + volume);

        //LpcWhisperiserEffect
//        LpcWhisperiserEffect lpcWhisperiserEffect = new LpcWhisperiserEffect(); //creepy
//        lpcWhisperiserEffect.setParams("amount:70");
//
//        //VolumeEffect
//        VolumeEffect volumeEffect = new VolumeEffect(); //be careful with this i almost got heart attack
//        volumeEffect.setParams("amount:0");

        //Apply the effects
        //----You can add multiple effects by using the method `getFullEffectAsString()` and + symbol to connect with the other effect that you want
        //----check the example below
        tts.getMarytts().setAudioEffects(stadiumEffect.getFullEffectAsString());// + "+" + stadiumEffect.getFullEffectAsString());

        //=========================================================================
        //===================== Now let's troll user ==============================
        //=========================================================================
        tts.speak(text, 2.0f, false, true);
    }
    private void BtnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRetourActionPerformed
        // TODO add your handling code here:
        panneauAdmin.setVisible(false);
        panneauTraduction.setVisible(true);
    }//GEN-LAST:event_BtnRetourActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        panneauAdmin.setVisible(true);
        panneauTraduction.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    private void choixLangueCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choixLangueCmbItemStateChanged
        // TODO add your handling code here:
        Map<String, String> allData;
        Object item = evt.getItem();
        tableMot.removeAll();
        if (item.toString().equalsIgnoreCase("yemba")) {
            allData = confYemba.loadAllIn();
            parcourirBtn.setEnabled(true);
            addWordBtn.setEnabled(true);
        } else if (item.toString().equalsIgnoreCase("bassa")) {
            allData = confBassa.loadAllIn();
            parcourirBtn.setEnabled(true);
            addWordBtn.setEnabled(true);
        } else {
            allData = new HashMap<>();
            parcourirBtn.setEnabled(false);
            addWordBtn.setEnabled(false);
        }

        DefaultTableModel model = (DefaultTableModel) tableMot.getModel();
        model.getDataVector().removeAllElements();
        Set keys = allData.keySet();
        Iterator iteratorKeys = keys.iterator();

        while (iteratorKeys.hasNext()) {
            String key = (String) iteratorKeys.next();
            //insert on first position by pushing down the existing rows
            //model.insertRow(0, new Object[]{key, allData.get(key)});
            //append at the end
            model.addRow(new Object[]{key, allData.get(key)});
        }
    }//GEN-LAST:event_choixLangueCmbItemStateChanged

    private void addWordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWordBtnActionPerformed
        // TODO add your handling code here:

        Map<String, String> allData;
        String motFr = motFrancais.getText().toLowerCase();
        String motTr = motTraduit.getText().toLowerCase();
        if (choixLangueCmb.getSelectedItem().toString().equalsIgnoreCase("yemba")) {
            if (motFr.equalsIgnoreCase(confYemba.getPropertyIn(motFr))) {
                confYemba.setPropertyIn(motFr, motTr);
                System.out.println("get yemba de " + motFr + " = " + confYemba.getPropertyIn(motFr));
            } else {
                JOptionPane.showMessageDialog(this, "Ce mot existe déjà dans le dictionnaire");
            }
            allData = confYemba.loadAllIn();

        } else if (choixLangueCmb.getSelectedItem().toString().equalsIgnoreCase("bassa")) {
            if (motFr.equalsIgnoreCase(confBassa.getPropertyIn(motFr))) {
                confBassa.setPropertyIn(motFr, motTr);
                System.out.println("get yemba de " + motFr + " = " + confBassa.getPropertyIn(motFr));
            } else {
                JOptionPane.showMessageDialog(this, "Ce mot existe déjà dans le dictionnaire");
            }
            allData = confBassa.loadAllIn();
        } else {
            allData = new HashMap<>();
        }
        DefaultTableModel model = (DefaultTableModel) tableMot.getModel();
        model.getDataVector().removeAllElements();
        Set keys = allData.keySet();
        Iterator iteratorKeys = keys.iterator();

        while (iteratorKeys.hasNext()) {
            String key = (String) iteratorKeys.next();
            //insert on first position by pushing down the existing rows
            model.insertRow(0, new Object[]{key, allData.get(key)});
            //append at the end
//            model.addRow(new Object[]{key, allData.get(key)});
        }
    }//GEN-LAST:event_addWordBtnActionPerformed

    private void importbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importbtnActionPerformed
        // TODO add your handling code here:
        if (!"".equals(fileToUpload)) {
            Map<String, String> allData = null;
            FileReader fr = null;
            try (BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(fileToUpload), "UTF8"))) {
                System.out.println("selected = " + choixLangueCmb.getSelectedItem());
                String line;
                if (choixLangueCmb.getSelectedItem().toString().equalsIgnoreCase("yemba")) {
                    while ((line = br.readLine()) != null) {
                        String[] tab = line.split("=");
                        if (tab.length == 2) {
                            confYemba.setPropertyIn(tab[0], tab[1]);
                        } else {
                            System.out.println("ligne " + line + " ignorée");
                        }
                    }
                    br.close();    //closes the stream and release the resources 
                    allData = confYemba.loadAllIn();
                } else if (choixLangueCmb.getSelectedItem().toString().equalsIgnoreCase("bassa")) {
                    while ((line = br.readLine()) != null) {
                        String[] tab = line.split("=");
                        if (tab.length == 2) {
                            confBassa.setPropertyIn(tab[0], tab[1]);
                        } else {
                            System.out.println("ligne " + line + " ignorée");
                        }
                    }
                    br.close();
                    allData = confBassa.loadAllIn();
                }
                DefaultTableModel model = (DefaultTableModel) tableMot.getModel();
                model.getDataVector().removeAllElements();
                Set keys = allData.keySet();
                Iterator iteratorKeys = keys.iterator();
                while (iteratorKeys.hasNext()) {
                    String key = (String) iteratorKeys.next();
                    model.insertRow(0, new Object[]{key, allData.get(key)});
                }
                JOptionPane.showMessageDialog(this, "Importation terminée !!!");
                fileToUpload = "";
                fileToImportTxf.setText("");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_importbtnActionPerformed

    private void parcourirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcourirBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Fichier texte", "txt");
        FileNameExtensionFilter filter2 = new FileNameExtensionFilter("Fichier properties", "properties");
        jfc.setFileFilter(filter);
        int returnVal = jfc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            fileToUpload = file.getAbsolutePath();
            fileToImportTxf.setText(fileToUpload);
        }
    }//GEN-LAST:event_parcourirBtnActionPerformed

    private void francaisTxtFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_francaisTxtFieldKeyReleased
        // TODO add your handling code here:
//        String motEnCours = "";
        if (!"".equals(francaisTxtField.getText()) && !francaisTxtField.getText().endsWith(" ")) {
            String[] tableauDesMots = francaisTxtField.getText().split(" ");
            String debutPhrase = "";
            for (int i = 0; i < tableauDesMots.length - 1; i++) {
                debutPhrase += tableauDesMots[i] + " ";
            }
            final String debut = debutPhrase;
            final String motEnCours = tableauDesMots[tableauDesMots.length - 1];
            if (motEnCours.length() >= 3) {
//                String[] obj = (String[]) allWords.stream()
//                        .filter(c -> c.startsWith(motEnCours))
//                        .collect(Collectors.toList()).toArray();
//                ArrayList<String> list = new ArrayList();
//                Collections.addAll(list, obj);
                popupmenu.removeAll();
                allWords.forEach((String s) -> {
                    if (s.startsWith(motEnCours)) {
                        JMenuItem item = new JMenuItem(s);
                        popupmenu.add(item);
                        item.addActionListener((ActionEvent e) -> {
                            francaisTxtField.setText(debut + e.getActionCommand());
                        });
                    }
                });
                if (popupmenu.getSubElements().length != 0) {
                    Caret caret = francaisTxtField.getCaret();
                    Point p = caret.getMagicCaretPosition();
                    popupmenu.show(francaisTxtField, (int) p.x, (int) p.y);
//                    popupmenu.requestFocus(false);
//                popupmenu.requestFocus();
//                popupmenu.grabFocus();
                }
            }
        }
    }//GEN-LAST:event_francaisTxtFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBassa;
    private javax.swing.JButton BtnRetour;
    private javax.swing.JButton BtnYemba;
    private javax.swing.JButton addWordBtn;
    private javax.swing.JTextArea bassaTxtField;
    private javax.swing.JComboBox<String> choixLangueCmb;
    private javax.swing.JTextField fileToImportTxf;
    private javax.swing.JTextArea francaisTxtField;
    private javax.swing.JButton importbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField motFrancais;
    private javax.swing.JTextField motTraduit;
    private javax.swing.JPanel panneauAdmin;
    private javax.swing.JPanel panneauTraduction;
    private javax.swing.JButton parcourirBtn;
    private javax.swing.JPopupMenu popupmenu;
    private javax.swing.JTable tableMot;
    private javax.swing.JSlider volumeBassa;
    private javax.swing.JSlider volumeYemba;
    private javax.swing.JTextArea yembaTxtField;
    // End of variables declaration//GEN-END:variables
}
